name: Get Citation Data

on: 
  page_build: 
  schedule:
    - cron: '0 8 * * *'  # 每天 UTC 时间 8:00 运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v2
      with:
        ref: main  # 指定分支

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-setuptools
        echo "System dependencies installed successfully"

    - name: Install Python Dependencies
      run: |
        cd ./google_scholar_crawler
        echo "Installing Python requirements..."
        pip install -r requirements.txt
        echo "Python dependencies installed successfully"

    - name: Run Google Scholar Crawler
      run: |
        echo "Starting Google Scholar data collection..."
        python main.py
        echo "Data collection completed"
        ls -la ./results/
      env:
        GOOGLE_SCHOLAR_ID: "NSHQsrAAAAAJ"

    - name: Configure Git
      run: |
        cd ./results
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        echo "Git configured successfully"

    - name: Commit and Push Changes
      run: |
        cd ./results
        git add *.json
        git status
        git commit -m "Updated Citation Data - $(date +'%Y-%m-%d %H:%M:%S')"
        echo "Changes committed successfully"
        
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git push "${remote_repo}" HEAD:google-scholar-stats --force
        echo "Changes pushed successfully"
      env:
        TOKEN: ${{ secrets.TOKEN }}

    - name: Verify Results
      run: |
        echo "Verifying results..."
        cd ./results
        ls -la
        echo "Results verification completed"


















# name: Get Citation Data

# on: 
#  page_build: 
#  schedule:
#   - cron:  '0 8 * * *'

# jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Install Reqs
#      run: |
#        sudo apt-get install python3-setuptools
#    - name: Run
#      run: |
#        cd ./google_scholar_crawler
#        pip install -r requirements.txt
#        python main.py
#        cd ./results
#        git init
#        git config --local user.name "${GITHUB_ACTOR}"
#        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
#        git add *.json
#        git commit -m "Updated Citation Data"
#        git push "${remote_repo}" HEAD:google-scholar-stats --force
#      env: 
#        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
