name: Get Citation Data

on: 
  page_build: 
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Reqs
        run: |
          sudo apt-get install python3-setuptools
      - name: Run
        run: |
          set -e

          echo "Starting the process..."

          # Navigate to the crawler directory
          cd ./google_scholar_crawler || { echo "Failed at step: cd ./google_scholar_crawler"; exit 1; }
          
          # Install required Python packages
          pip install -r requirements.txt || { echo "Failed at step: pip install -r requirements.txt"; exit 1; }

          # Run the Python script
          python main.py || { echo "Failed at step: python main.py"; exit 1; }

          # Navigate to the results directory
          cd ./results || { echo "Failed at step: cd ./results"; exit 1; }

          # Initialize git repository
          git init || { echo "Failed at step: git init"; exit 1; }

          # Configure git user
          git config --local user.name "${GITHUB_ACTOR}" || { echo "Failed at step: git config --local user.name"; exit 1; }

          # Prepare remote repo
          export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" || { echo "Failed at step: export remote_repo"; exit 1; }

          # Add files to git
          git add *.json || { echo "Failed at step: git add *.json"; exit 1; }

          # Commit changes
          git commit -m "Updated Citation Data" || { echo "Failed at step: git commit"; exit 1; }

          # Push changes to remote repository
          git push "${remote_repo}" HEAD:google-scholar-stats --force || { echo "Failed at step: git push"; exit 1; }
          
          echo "Process completed successfully!"
        env: 
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}



















# name: Get Citation Data

# on: 
#  page_build: 
#  schedule:
#   - cron:  '0 8 * * *'

# jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Install Reqs
#      run: |
#        sudo apt-get install python3-setuptools
#    - name: Run
#      run: |
#        cd ./google_scholar_crawler
#        pip install -r requirements.txt
#        python main.py
#        cd ./results
#        git init
#        git config --local user.name "${GITHUB_ACTOR}"
#        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
#        git add *.json
#        git commit -m "Updated Citation Data"
#        git push "${remote_repo}" HEAD:google-scholar-stats --force
#      env: 
#        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
